kind: Service
apiVersion: v1
metadata:
  name: myproject
  labels:
    app: myproject
spec:
  type: NodePort
  selector:
    app: myproject
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
        version: v1
    spec:
      containers:
      - name: myproject
        image: myproject
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
